module.exports = {
  '1': ['glslify'],
  '2': ['glslify'],
  '3': ['glslify'],
  '4': ['glslify'],
  '5': ['glslify'],
  '6': ['glslify'],
  '7': ['glslify'],
  '8': ['glslify'],
  '11': ['glslify'],
  '14': ['glslify'],
  '15': ['glslify'],
  '17': ['glslify'],
  '19': ['brfs'],
  '21': ['glslify'],
  '23': ['brfs', 'glslify'],
  '26': ['glslify'],
  '27': ['glslify'],
  '28': ['glslify'],
  '29': ['glslify'],
  '30': ['glslify'],
  'grid': ['hbsfy', 'brfs']
}
